In [54]:
import pandas as pd

In [55]:
df=pd.read_csv("Titanic-Dataset.csv")

In [56]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [57]:
df.shape

(891, 12)

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [59]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [60]:
df.duplicated().sum()

np.int64(0)

In [61]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [62]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [63]:
df["Age"].isnull().sum()

np.int64(177)

In [64]:
df["Age"].median()

np.float64(28.0)

In [65]:
df["Age"]=df["Age"].fillna(df["Age"].median())

In [66]:
df["Age"].isnull().sum()

np.int64(0)

In [67]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [68]:
df["Cabin"].isnull().sum()

np.int64(687)

In [69]:
df["Embarked"].isnull().sum()

np.int64(2)

In [70]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [71]:
df["Embarked"].mode()

0    S
Name: Embarked, dtype: str

In [72]:
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])

In [73]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [74]:
df["Cabin"].isnull().sum()

np.int64(687)

In [75]:
df["Cabin"].value_counts().head(10)

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F33            3
E101           3
F2             3
D              3
C22 C26        3
C123           2
D33            2
Name: count, dtype: int64

In [24]:
df["Cabin"].isnull().mean()*100

np.float64(77.10437710437711)

In [76]:
df["Cabin"]=df["Cabin"].fillna("unknown")

In [77]:
df["Cabin"].isnull().sum()

np.int64(0)

In [78]:

df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [28]:
df["Ticket"].value_counts().head(10)

Ticket
347082          7
1601            7
CA. 2343        7
3101295         6
CA 2144         6
347088          6
382652          5
S.O.C. 14879    5
349909          4
347077          4
Name: count, dtype: int64

In [79]:
df["Ticket"].dtype

In [80]:
df["Fare"].dtype

dtype('float64')

In [81]:
df["PassengerId"].dtype

dtype('int64')

In [82]:
df["PassengerId"]=df["PassengerId"].astype("string")

In [83]:
df["PassengerId"].dtype

In [84]:
df["Age"].describe()

count    891.000000
mean      29.361582
std       13.019697
min        0.420000
25%       22.000000
50%       28.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [85]:
df["Age"].quantile([0.25,0.75])

0.25    22.0
0.75    35.0
Name: Age, dtype: float64

In [86]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

print(IQR)

13.0

In [87]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print(lower_limit)
print(upper_limit)

2.5
54.5

In [88]:
age_outliers = df[(df["Age"] < lower_limit) | (df["Age"] > upper_limit)]

age_outliers.shape

(66, 12)

age_outliers["Age"].sort_values().unique()

Outlier Decision: IQR identified some Age values as statistical outliers. However, these values represent valid passenger ages, including children and elderly passengers. Therefore, they were retained

In [89]:
df["Fare"].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [90]:
Q1_fare = df["Fare"].quantile(0.25)
Q3_fare = df["Fare"].quantile(0.75)

IQR_fare = Q3_fare - Q1_fare

print(IQR_fare)

23.0896

In [91]:
lower_fare =Q1_fare
IQR_fare
upper_fare=Q3_fare
IQR_fare
print("lower_fare")
print("upper_fare")

lower_fare
upper_fare

In [92]:
Q1_fare = df["Fare"].quantile(0.25)
Q3_fare = df["Fare"].quantile(0.75)

IQR_fare = Q3_fare - Q1_fare

lower_fare = Q1_fare - 1.5 * IQR_fare
upper_fare = Q3_fare + 1.5 * IQR_fare

print("Lower limit:", lower_fare)
print("Upper limit:", upper_fare)

Lower limit: -26.724
Upper limit: 65.6344

In [93]:
fare_outliers = df[(df["Fare"] < lower_fare) | (df["Fare"] > upper_fare)]

fare_outliers.shape

(116, 12)

In [94]:
fare_outliers["Fare"].describe()

count    116.000000
mean     128.291629
std       84.636908
min       66.600000
25%       78.189600
50%       90.000000
75%      147.778100
max      512.329200
Name: Fare, dtype: float64

In [95]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [96]:
df.duplicated().sum()

np.int64(0)

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    string
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    str
 11  Embarked     891 non-null    str
dtypes: float64(2), int64(4), str(5), string(1)
memory usage: 125.9 KB

In [98]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,unknown,S

In [99]:
df.to_csv("Titanic-Cleaned.csv",index=False)

## 1. Data Quality Report

In [100]:
print("Null values per column:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Null values per column:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Duplicate rows:
0

Data types:
PassengerId     string
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [101]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

### Data Quality Findings

The dataset contains 891 records. Numerical columns were checked for their statistical ranges and potential anomalies. Age ranges from 0.42 to 80 years, while Fare ranges from 0 to 512.3292. These ranges were further examined using the IQR method for outlier detection.

## 2. Missing Data Handling

### Age

Missing Age values were replaced with the median because Age is a numerical variable and the median is less affected by extreme values.

### Embarked

Missing Embarked values were replaced with the mode because Embarked is a categorical variable, and the mode represents the most frequently occurring category.

### Cabin

The Cabin column contains a large number of missing values. Instead of removing these rows, the missing values were replaced with "Unknown" to preserve the available records.

## 3.Duplicate Removal

In [102]:
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:",duplicate_count)

Number of duplicate rows: 0

No duplicate rows were found in the dataset,so no duplicate records were removed.

## 4. Standardisation

In [103]:
print("Sex valiues:")
print(df["Sex"].unique())

print("\nEmbarked values:")
print(df["Embarked"].unique())

Sex valiues:
<ArrowStringArray>
['male', 'female']
Length: 2, dtype: str

Embarked values:
<ArrowStringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

The categorical values were checked for consistency. The values in the Sex and Embarked columns were already in a consistent format, so no standardisation was required.

## 5. Outlier Detection

### Age Outliers

In [104]:
Q1_age = df["Age"].quantile(0.25)
Q3_age = df["Age"].quantile(0.75)

IQR_age = Q3_age - Q1_age

lower_age = Q1_age - 1.5 * IQR_age
upper_age = Q3_age + 1.5 * IQR_age

age_outliers = df[(df["Age"] < lower_age) | (df["Age"] > upper_age)]

print("Lower limit:", lower_age)
print("Upper limit:", upper_age)
print("Number of Age outliers:", age_outliers.shape[0])

Lower limit: 2.5
Upper limit: 54.5
Number of Age outliers: 66

66 Age values were identified as statistical outliers using the IQR method. These values were retained because the ages are valid observations and are not necessarily data errors.

### Fare Outliers

In [105]:
Q1_fare = df["Fare"].quantile(0.25)
Q3_fare = df["Fare"].quantile(0.75)

IQR_fare = Q3_fare - Q1_fare

lower_fare = Q1_fare - 1.5 * IQR_fare
upper_fare = Q3_fare + 1.5 * IQR_fare

fare_outliers = df[(df["Fare"] < lower_fare) | (df["Fare"] > upper_fare)]

print("Lower limit:", lower_fare)
print("Upper limit:", upper_fare)
print("Number of Fare outliers:", fare_outliers.shape[0])

Lower limit: -26.724
Upper limit: 65.6344
Number of Fare outliers: 116

116 Fare values were identified as statistical outliers using the IQR method. These values were retained because high fare values can represent valid ticket prices and are not necessarily data errors.

## 6. Data Type Correction

In [109]:
print(df.dtypes)

PassengerId     string
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

The data types of the columns were checked and found to be appropriate. ID and text-based columns are stored as strings, while numerical columns such as Age and Fare use appropriate numeric data types.

## 7. Before Vs After Cleaning Summary

In [110]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Data types:")
print(df.dtypes)

Rows: 891
Columns: 12
Missing values: 0
Duplicate rows: 0
Data types:
PassengerId     string
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

| Metric | Before Cleaning | After Cleaning |
|---|---:|---:|
| Number of Rows | 891 | 891 |
| Number of Columns | 12 | 12 |
| Missing Values | 866 | 0 |
| Duplicate Rows | 0 | 0 |

## 8. Exporting Cleaned Dataset

In [113]:
df.to_csv("Titanic-Cleaned.csv",index=False)

## 9. Conclusion

The Titanic dataset was cleaned by handling missing values, checking duplicate records, standardising categorical values, detecting outliers, and verifying appropriate data types. After cleaning, the dataset contains 891 rows, 12 columns, no missing values, and no duplicate records. The cleaned dataset was saved as Titanic-Cleaned.csv.